---
extends:
    - "airbnb-base"
env:
    mocha: true
    browser: true
parser: "babel-eslint"
settings:
    import/resolver:
        node:
            extensions:
                - ".js"
            moduleDirectory:
                - "src"
                - "node_modules"
rules:
    # indent with 4 spaces
    indent:
        - "warn"
        - 4
        - SwitchCase: 1
    # set max-length to 120, 80 is too narrow
    max-len:
        - "warn"
        - "code": 120
    # allow underscore-dangles
    no-underscore-dangle: "off"
    # don't use semi-colons
    semi:
        - "warn"
        - "never"
    # classes can have methods that don't use this (helper methods)
    class-methods-use-this: 0
    import/no-extraneous-dependencies:
        - "warn":
            packageDir: "./"
    linebreak-style: 0
    import/no-named-as-default: 0
    # Allow no parens around arrow
    arrow-parens: "off"
    no-param-reassign: 0
    no-unused-vars:
        - "warn"
        - "vars": "all"
          "args": "after-used"
          "ignoreRestSiblings": false
